//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispensarioMedicoUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmacos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farmacos()
        {
            this.Medicamentos = new HashSet<Medicamentos>();
        }
    
        public int IdFarmaco { get; set; }
        public string Nombre { get; set; }
        public string PrincipioActivo { get; set; }
        public int IdViaAdministracion { get; set; }
        public string FormaFarmaceutica { get; set; }
        public bool Estado { get; set; }
    
        public virtual ViaAdmin ViaAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamentos> Medicamentos { get; set; }
    }
}
