//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispensarioMedicoUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamentos()
        {
            this.Registro_Visitas = new HashSet<Registro_Visitas>();
        }
    
        public int IdMedicamento { get; set; }
        public string Nombre { get; set; }
        public int IdFarmaco { get; set; }
        public int IdMarca { get; set; }
        public int IdUbicacion { get; set; }
        public int Cantidad { get; set; }
        public string Dosis { get; set; }
        public bool Estado { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Farmacos Farmacos { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Visitas> Registro_Visitas { get; set; }
    }
}
