//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispensarioMedicoUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.Registro_Visitas = new HashSet<Registro_Visitas>();
        }
    
        public int IdPaciente { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public int NoCarnet { get; set; }
        public int IdTipoPaciente { get; set; }
        public bool Estado { get; set; }
    
        public virtual TipoPaciente TipoPaciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Visitas> Registro_Visitas { get; set; }
    }
}
